import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Coins } from "lucide-react";

export const MintTokenForm = ({ onSuccess }: { onSuccess: () => void }) => {
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();
  const [formData, setFormData] = useState({
    farmName: '',
    amountKwh: '',
    pricePerKwh: '',
  });

  const handleMint = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const { data: userData } = await supabase.auth.getUser();
      if (!userData.user) throw new Error('Usuário não autenticado');

      // Generate unique token ID
      const tokenId = `TOKEN${Date.now()}${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
      const farmId = crypto.randomUUID();

      // Insert token
      const { data: tokenData, error: tokenError } = await supabase
        .from('energy_tokens')
        .insert({
          token_id: tokenId,
          farm_id: farmId,
          farm_name: formData.farmName,
          amount_kwh: parseFloat(formData.amountKwh),
          price_per_kwh: parseFloat(formData.pricePerKwh),
          created_by: userData.user.id,
          status: 'available',
          metadata: {
            creator_id: userData.user.id,
            created_at: new Date().toISOString(),
          },
        })
        .select()
        .single();

      if (tokenError) throw tokenError;

      // Create mint transaction
      const { error: txError } = await supabase
        .from('token_transactions')
        .insert([{
          transaction_hash: '', // Will be auto-generated by trigger
          token_id: tokenData.id,
          to_user_id: userData.user.id,
          amount_kwh: parseFloat(formData.amountKwh),
          transaction_type: 'mint',
          status: 'confirmed',
          metadata: {
            farm_name: formData.farmName,
            token_identifier: tokenId,
          },
        }]);

      if (txError) throw txError;

      toast({
        title: "Token criado com sucesso!",
        description: `${formData.amountKwh} kWh tokenizados da fazenda ${formData.farmName}`,
      });

      setFormData({ farmName: '', amountKwh: '', pricePerKwh: '' });
      onSuccess();
    } catch (error: any) {
      console.error('Error minting token:', error);
      toast({
        title: "Erro ao criar token",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Coins className="w-5 h-5 text-purple-600" />
          <CardTitle>Criar Novo Token de Energia</CardTitle>
        </div>
        <CardDescription>
          Tokenize créditos de energia de suas fazendas solares
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleMint} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="farmName">Nome da Fazenda Solar</Label>
            <Input
              id="farmName"
              placeholder="Ex: Fazenda Solar Nordeste"
              value={formData.farmName}
              onChange={(e) => setFormData({ ...formData, farmName: e.target.value })}
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="amountKwh">Quantidade (kWh)</Label>
              <Input
                id="amountKwh"
                type="number"
                step="0.01"
                min="0.01"
                placeholder="1000"
                value={formData.amountKwh}
                onChange={(e) => setFormData({ ...formData, amountKwh: e.target.value })}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="pricePerKwh">Preço por kWh (R$)</Label>
              <Input
                id="pricePerKwh"
                type="number"
                step="0.01"
                min="0.01"
                placeholder="0.75"
                value={formData.pricePerKwh}
                onChange={(e) => setFormData({ ...formData, pricePerKwh: e.target.value })}
                required
              />
            </div>
          </div>

          {formData.amountKwh && formData.pricePerKwh && (
            <div className="bg-purple-50 dark:bg-purple-950/20 p-4 rounded-lg border border-purple-200 dark:border-purple-800">
              <p className="text-sm text-muted-foreground mb-1">Valor Total do Token</p>
              <p className="text-2xl font-bold text-purple-600">
                R$ {(parseFloat(formData.amountKwh) * parseFloat(formData.pricePerKwh)).toFixed(2)}
              </p>
            </div>
          )}

          <Button type="submit" className="w-full bg-purple-600 hover:bg-purple-700" disabled={loading}>
            {loading ? (
              <span className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
                Criando Token...
              </span>
            ) : (
              <span className="flex items-center gap-2">
                <Coins className="w-4 h-4" />
                Criar Token
              </span>
            )}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
};
