import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Zap, ShoppingCart, MapPin, TrendingDown } from "lucide-react";

interface Token {
  id: string;
  token_id: string;
  farm_name: string;
  amount_kwh: number;
  price_per_kwh: number;
  total_value: number;
  status: string;
  created_at: string;
  metadata: any;
}

export const TokenMarketplace = () => {
  const [tokens, setTokens] = useState<Token[]>([]);
  const [loading, setLoading] = useState(true);
  const [purchasing, setPurchasing] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    fetchAvailableTokens();
  }, []);

  const fetchAvailableTokens = async () => {
    try {
      const { data, error } = await supabase
        .from('energy_tokens')
        .select('*')
        .eq('status', 'available')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setTokens(data || []);
    } catch (error) {
      console.error('Error fetching tokens:', error);
      toast({
        title: "Erro ao carregar tokens",
        description: "Não foi possível carregar os tokens disponíveis",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handlePurchase = async (token: Token) => {
    setPurchasing(token.id);

    try {
      const { data: userData } = await supabase.auth.getUser();
      if (!userData.user) throw new Error('Usuário não autenticado');

      // Update token status to sold
      const { error: updateError } = await supabase
        .from('energy_tokens')
        .update({ status: 'sold' })
        .eq('id', token.id);

      if (updateError) throw updateError;

      // Create transfer transaction
      const { error: txError } = await supabase
        .from('token_transactions')
        .insert([{
          transaction_hash: '', // Auto-generated by trigger
          token_id: token.id,
          from_user_id: token.metadata?.creator_id || null,
          to_user_id: userData.user.id,
          amount_kwh: token.amount_kwh,
          transaction_type: 'transfer',
          status: 'confirmed',
          metadata: {
            farm_name: token.farm_name,
            token_identifier: token.token_id,
            purchase_price: token.total_value,
          },
        }]);

      if (txError) throw txError;

      toast({
        title: "Compra realizada com sucesso! 🎉",
        description: `Você adquiriu ${token.amount_kwh} kWh da ${token.farm_name}`,
      });

      // Refresh tokens list
      fetchAvailableTokens();
    } catch (error: any) {
      console.error('Error purchasing token:', error);
      toast({
        title: "Erro na compra",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setPurchasing(null);
    }
  };

  const calculateMonthlyDiscount = (amountKwh: number, pricePerKwh: number) => {
    // Assuming average consumption of 450 kWh/month and R$ 0.85/kWh regular price
    const regularPrice = 0.85;
    const discount = ((regularPrice - pricePerKwh) / regularPrice) * 100;
    return discount.toFixed(1);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
      </div>
    );
  }

  if (tokens.length === 0) {
    return (
      <Card>
        <CardContent className="py-12">
          <div className="text-center">
            <Zap className="w-16 h-16 mx-auto mb-4 text-muted-foreground opacity-50" />
            <h3 className="text-xl font-semibold mb-2">Nenhum token disponível</h3>
            <p className="text-muted-foreground">
              Novos tokens de energia serão listados em breve
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
      {tokens.map((token) => (
        <Card key={token.id} className="hover:shadow-lg transition-shadow border-2 hover:border-primary/50">
          <CardHeader>
            <div className="flex items-start justify-between mb-2">
              <Badge variant="default" className="bg-green-600">
                <Zap className="w-3 h-3 mr-1" />
                Disponível
              </Badge>
              <div className="text-right">
                <p className="text-2xl font-bold text-primary">
                  {calculateMonthlyDiscount(token.amount_kwh, parseFloat(token.price_per_kwh.toString()))}%
                </p>
                <p className="text-xs text-muted-foreground">desconto</p>
              </div>
            </div>
            
            <CardTitle className="text-xl flex items-center gap-2">
              <MapPin className="w-5 h-5 text-muted-foreground" />
              {token.farm_name}
            </CardTitle>
            <CardDescription className="font-mono text-xs">
              {token.token_id}
            </CardDescription>
          </CardHeader>
          
          <CardContent className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-muted/50 rounded-lg p-3">
                <p className="text-xs text-muted-foreground mb-1">Energia</p>
                <p className="text-lg font-bold">{token.amount_kwh} kWh</p>
              </div>
              <div className="bg-muted/50 rounded-lg p-3">
                <p className="text-xs text-muted-foreground mb-1">Preço/kWh</p>
                <p className="text-lg font-bold">R$ {parseFloat(token.price_per_kwh.toString()).toFixed(2)}</p>
              </div>
            </div>

            <div className="bg-accent/10 rounded-lg p-4 border border-accent/20">
              <div className="flex items-center gap-2 mb-1">
                <TrendingDown className="w-4 h-4 text-accent" />
                <span className="text-sm font-semibold">Valor Total</span>
              </div>
              <p className="text-2xl font-bold text-accent">
                R$ {parseFloat(token.total_value.toString()).toFixed(2)}
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                Economia garantida por {Math.ceil(token.amount_kwh / 450)} meses*
              </p>
            </div>

            <Button 
              className="w-full" 
              size="lg"
              onClick={() => handlePurchase(token)}
              disabled={purchasing === token.id}
            >
              {purchasing === token.id ? (
                <span className="flex items-center gap-2">
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
                  Processando...
                </span>
              ) : (
                <span className="flex items-center gap-2">
                  <ShoppingCart className="w-4 h-4" />
                  Comprar Token
                </span>
              )}
            </Button>

            <p className="text-xs text-muted-foreground text-center">
              * Baseado em consumo médio de 450 kWh/mês
            </p>
          </CardContent>
        </Card>
      ))}
    </div>
  );
};
